Vagrant.configure('2') do |config|
	config.vm.provider :proxmox do |proxmox|
		proxmox.endpoint = 'https://your.proxmox.server/api2/json'
		proxmox.user_name = 'vagrant'
		proxmox.password = 'password'
		proxmox.os_template = 'local:vztmpl/template.tgz'
		proxmox.vm_id_range = 900..910
		proxmox.vm_name_prefix = 'vagrant_test_'
		proxmox.vm_memory = 256
		proxmox.task_timeout = 30
		proxmox.task_status_check_interval = 1

	end

	config.vm.define :box, primary: true do |box|
		box.vm.box = 'dummy'
	end
end
