Vagrant.configure('2') do |config|
	config.vm.provider :proxmox do |proxmox|
		proxmox.endpoint = 'https://proxmox.example.com/api2/json'
		proxmox.user_name = 'vagrant'
		proxmox.password = 'password'
		proxmox.os_template = 'local:vztmpl/template.tar.gz'
		proxmox.vm_id_range = 900..910
		proxmox.vm_name_prefix = 'vagrant_test_'
		proxmox.vm_memory = 256
	end

	config.vm.define :machine, primary: true do |machine|
		machine.vm.box = 'b681e2bc-617b-4b35-94fa-edc92e1071b8'
	end
end
